# -*- coding: utf-8 -*-
"""Dummy Variables & One Hot Encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXRj6pKRTQDGamSe7-EXxceLfMrmkAQL
"""

import pandas as pd
from google.colab import files
import io

data=files.upload()

df=pd.read_csv(io.StringIO(data['area_encoding.csv'].decode('utf-8')))
df

dummies=pd.get_dummies(df.town)
dummies

merged=pd.concat([df,dummies],axis='columns')
merged



final = merged.drop(['robinsville','west windsor'],axis='columns')
final

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dfle=df
dfle.town=le.fit_transform(dfle.town)
dfle

X=dfle[['town','area']].values
X

Y=dfle.price
Y

from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
X=ohe.fit_transform(X).toarray()
X

X=X[:,1:]
X

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,Y)

model.predict(X)